### ISSUE TITLE
Compatibility with LanguageTabs (core)

### ISSUE THREAD

**Issue by somatonic** [apeisa/Fredi#12]
Since now Ryan put LanguageTabs in core and the code to load when Fredi process is loading is now missing and so doesn't work anymore with Fredi modals. This was something I added to LanguageTabs via a PR... https://github.com/adamspruijt/LanguageFieldTabs/blob/master/LanguageFieldTabs.module#L42 , but Ryan got an older version it seems and it's not in anymore.

Now I'm not sure which modules should check for the existing of the other anymore. :) Since Lanugage Tabs listens only to ProcessPageEdit.

Now trying if Fredi could support LanguageTabs. And I got it working again with adding:

if($this->modules->isInstalled("LanguageTabs")){
	$this->modules->get("LanguageTabs")->loadTabs();
}

in the ___execute of FrediProcess.module 

But not sure about if LanguageTabs should really use ProcessPageEdit::execute to load and why not on all forms? What you think?

**Comment by apeisa** [comment]
This issue is no longer valid in latest version (which uses ProcessPageEdit for form rendering).
