### ISSUE TITLE
$this->fields problematic and it shows with latest dev

### ISSUE THREAD

**Issue by somatonic** [apeisa/Fredi#17]
I get an error in my Fork of fredi I'm using since some time. I need to fix the module every now and then.

TemplateFile: Field 'frediAll' is not applicable to this page#0 /.../wire/core/Modules.php(387): ProcessPageEdit->init() ...

This seems that the use of $this->fields as a property was always problematic as this also points to $fields API same like $this->pages. I think new way to do it in future is $this->wire("pages"), but anyway I get this error because $this->fields = "frediAll"; etc.

Just wanted to mention.

**Comment by apeisa** [comment]
Soma, not sure I follow. What's the error you get and what is your fix?

**Comment by apeisa** [comment]
Now I got it - it's naming class between Fredi's fields property and PW's fields "global".

**Comment by apeisa** [comment]
Should be fixed now.
